export function aiGuideText(): string {
  return [
    "# vspec AI Guide",
    "",
    "## 작성 원칙",
    "",
    "- 사용자의 요청, PRD, 기존 문서가 한국어이면 use case 본문도 한국어로 작성한다.",
    "- 파일명, key, actor/stakeholder `name` 같은 식별자는 영문 kebab-case를 유지해도 된다.",
    "- title, display_name, stakeholder interest, precondition, trigger, scenario step, extension, guarantee, notes는 사용자의 언어를 따른다.",
    "- 모든 scenario step은 E2E 테스트의 When/Then으로 옮길 수 있을 만큼 관찰 가능한 행동과 결과를 담는다.",
    "- `specs/glossary.md`의 Preferred Terms를 우선 사용하고 Avoid Terms의 모호한 표현을 피한다.",
    "",
    "## 기본 흐름",
    "",
    "1. 저장소 루트에서 `vspec init --key VSPEC`를 실행한다.",
    "2. 참조 actor를 `vspec actor create --name developer --display-name \"개발자\"`로 만든다.",
    "3. 참조 stakeholder를 `vspec stakeholder create --name vooster --display-name \"Vooster\"`로 만든다.",
    "4. `vspec usecase create --title \"유스케이스를 작성한다\" --primary-actor developer`로 use case를 시작한다.",
    "5. markdown을 직접 편집하거나 `vspec usecase add-stakeholder`, `vspec step add`, `vspec usecase set`을 사용한다.",
    "6. `vspec doctor <KEY>`를 실행해 오류와 품질 경고를 확인한다.",
    "7. 준비되면 `vspec export gherkin <KEY>`로 feature 파일을 만든다.",
    "",
    "Files under `specs/` are the source of truth. 서버, 데이터베이스, 네트워크 서비스 없이 로컬 파일만 사용한다.",
  ].join("\n");
}
